Questão 1 - UM DETERMINADO CLUBE DE FUTEBOL PRETENDE CLASSIFICAR SEUS ATLETAS EM CATEGORIAS E PARA ISTO ELE CONTRATOU UM PROGRAMADOR PARA CRIAR UM PROGRAMA QUE EXECUTASSE ESTA TAREFA. PARA ISSO O CLUBE CRIOU UMA TABELA QUE CONTINHA A FAIXA ETÁRIA DO ATLETA E SUA CATEGORIA. A TABELA ESTÁ DEMONSTRADA ABAIXO: IDADE CATEGORIA DE 05 A 10 INFANTIL DE 11 A 15 JUVENIL DE 16 A 20 JUNIOR DE 21 A 25 PROFISSIONAL CONSTRUA UM PROGRAMA QUE SOLICITE O NOME EA IDADE DE UM ATLETA E IMPRIMA A SUA CATEGORIA.

Questão 2 - O PROGRAMA DE UMA LOJA DE MÓVEIS MOSTRA O SEGUINTE MENU NA TELA DE VENDAS: 1-VENDA A VISTA 2-VENDA A PRAZO 30 DIAS 3-VENDA A PRAZO 60 DIAS 4-VENDA A PRAZO COM 90 DIAS 5-VENDA COM CARTÃO DE DÉBITO 6-VENDA COM CARTÃO DE CRÉDITO ESCOLHA A OPÇÃO:

Questão 3 - FAÇA UM PROGRAMA QUE RECEBA O VALOR DA VENDA, ESCOLHA A CONDIÇÃO DE PAGAMENTO NO MENU E MOSTRE O TOTAL DA VENDA FINAL CONFORME CONDIÇÕES A SEGUIR: VENDA A VISTA - DESCONTO DE 10% VENDA A PRAZO 30 DIAS - DESCONTO DE 5% VENDA A PRAZO 60 DIAS - MESMO PREÇO VENDA A PRAZO 90 DIAS - ACRÉSCIMO DE 5% VENDA COM CARTÃO DE DÉBITO - DESCONTO DE 8% VENDA COM CARTÃO DE CRÉDITO - DESCONTO DE 7%

Questão 4 - FAÇA UM PROGRAMA QUE LÊ QUATRO VALORES: I, A, BEC, ONDE I É UM NÚMERO INTEIRO E POSITIVO EA, B, EC SÃO QUAISQUER VALORES REAIS. O PROGRAMA DEVE ESCREVER OS VALORES LIDOS E: • SE I = 1, ESCREVER OS TRÊS VALORES A, BEC EM ORDEM CRESCENTE; • SE I = 2, ESCEVER OS TRÊS VALORES A, BEC EM ORDEM DECRESCENTE; • SE I = 3, ESCREVER OS TRÊS VALORES A, B, EC DE FORMA QUE O MAIOR VALOR FIQUE ENTRE OS OUTROS DOIS; • SE I NÃO FOR UM DOS TRÊS VALORES ACIMA, DAR UMA MENSAGEM INDICANDO ISTO.

Questão 5 - CRIE UM ALGORITMO QUE RECEBA AS NOTAS DE 10 ALUNOS EM UMA DISCIPLINA E CALCULE A MÉDIA DA TURMA.

Questão 6 - ELABORE UM ALGORITMO QUE SOLICITE AO USUÁRIO QUE INSIRA 10 NÚMEROS INTEIROS E ENTÃO APRESENTE O MAIOR E O MENOR VALOR DENTRE ESSES NÚMEROS.

Questão 7 - DESENVOLVA UM ALGORITMO QUE LEIA 15 NÚMEROS INTEIROS E APRESENTE QUANTOS SÃO PARES E QUANTOS SÃO ÍMPARES.

Questão 8 - CRIE UM ALGORITMO QUE SOLICITE AO USUÁRIO QUE INSIRA 10 NÚMEROS INTEIROS EM UM VETOR E DEPOIS PEÇA PARA ELE DIGITAR UM NÚMERO PARA BUSCAR NO VETOR. O ALGORITMO DEVE INFORMAR SE O NÚMERO ESTÁ PRESENTE NO VETOR E EM QUAL POSIÇÃO, CASO ESTEJA.

Questão 9 - IMPLEMENTE UM ALGORITMO PARA ORDENAR UM VETOR DE NÚMEROS INTEIROS EM ORDEM CRESCENTE OU DECRESCENTE.

Questão 10 - ELABORE UM ALGORITMO QUE RECEBA UM VETOR DE NÚMEROS INTEIROS E IDENTIFIQUE A MAIOR SEQUÊNCIA CRESCENTE PRESENTE NESSE VETOR.

Questão 11 - ESCREVA UM ALGORITMO QUE TROQUE OS VALORES DE DUAS VARIÁVEIS INTEIRAS USANDO VETORES.

Questão 12 - DESENVOLVA UM ALGORITMO QUE REALIZE A SOMA DE DOIS VETORES DE MESMO TAMANHO, CRIANDO UM TERCEIRO VETOR QUE ARMAZENE O RESULTADO.

Questão 13 - CRIE UM ALGORITMO QUE RECEBA DOIS VETORES DE MESMO TAMANHO E CALCULE O PRODUTO ESCALAR ENTRE ELES.
